- id: '1551584740236'
  alias: Carriage Lights On at Sunset
  trigger:
  - event: sunset
    offset: -00:15:00
    platform: sun
  condition: []
  action:
  - service: switch.turn_on
    entity_id: switch.ge_45609_on_off_relay_switch_switch
- id: '1551584934602'
  alias: Carriage Lights Off at Sunrise
  trigger:
  - event: sunrise
    offset: +00:15:00
    platform: sun
  condition: []
  action:
  - service: switch.turn_off
    entity_id: switch.ge_45609_on_off_relay_switch_switch
